import { Sandbox } from "@e2b/code-interpreter";
import type { AgentResult, TextMessage } from "@inngest/agent-kit";

export async function getSandbox(sandboxId: string) {
  const sandbox = await Sandbox.connect(sandboxId);
  return sandbox;
}

type AssistantMessage = TextMessage | undefined;
export async function getLastMessageContent(result: AgentResult) {
  /** Find the last message generated by assistants */
  const lastAssistantMessageIndex = result.output.findLastIndex(
    (message) => message.role === "assistant",
  );
  const message = result.output[lastAssistantMessageIndex] as AssistantMessage;

  /** No generate messages yet */
  if (!message?.content) return undefined;

  /**
   * Sometimes the response can be an array of string,
   * in this case, the value is joined in a single string and pass as is.
   */
  if (typeof message.content !== "string") {
    return message.content.map((c) => c.text).join("");
  }

  /** Last message was found and is of type string */
  return message.content;
}
