import StyledComponentsRegistry from "@/lib/styles-registry";

import { ClientProvider } from "@/providers";
import { Toaster } from "sonner";

import AppLayout from "./_layout";

import type { Metadata } from "next";

const metadataHead = {
  title: "Foundation UI - NextJS App",
  description: "Auto-generated by Foundation UI",
};

export const metadata: Metadata = {
  ...metadataHead,
  openGraph: {
    ...metadataHead,
    images: [
      {
        url: "",
        width: 1200,
        height: 630,
        alt: "svgjsx.dev Banner",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    ...metadataHead,
    card: "summary_large_image",
    images: [""],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <ClientProvider>
        <Toaster
          toastOptions={{
            style: {
              borderRadius: "var(--measurement-medium-30)",
              borderColor: "var(--font-color-alpha-10)",
              background: "var(--body-color)",
              color: "var(--font-color)",
              fontSize: "var(--fontsize-medium-10)",
            },
          }}
        />

        <html lang="en">
          <body>
            <AppLayout>{children}</AppLayout>
            <div id="portal-container" />
          </body>
        </html>
      </ClientProvider>
    </StyledComponentsRegistry>
  );
}
